version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: es-compose
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  edmond-ql:
    image: kkkom/edmond-ql:latest
    container_name: edmond-ql-compose
    environment:
      - book-api-url=https://api.openbd.jp/v1/get?isbn=
      - elasticsearch-url=http://es-compose:9200
      - schema-file=edmond-schema.edn
      - port=8888
    ports:
      - 8888:8888


volumes:
  esdata1:
    driver: local

