version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: es-compose
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - esnet
  elasticsearch2:
    image: kkkom/edmond-ql:latest
    container_name: edmond-ql-compose
    ports:
      - 8888:8888
    networks:
    - esnet

volumes:
  esdata1:
    driver: local


networks:
  esnet: